import { v4 as uuid } from "uuid";
import {  product1, product2, product3, product4, product5, product6, product7, product8, product9, product10, product11, product12, product13, product14, product15, product16, product17, product18, product19, product20, product21, product22, product23} from "../../assets"

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Ultra HD (4K) LED Smart",
    brand: "Motorola",
    price: "5000",
    priceBefore:"16000",
    discount:"50",
    rating:"4.5",
    inStock:true,
    isFeatured:true,
    isLatest:false,
    badge:"",
    imgSrc:product1,
    categoryName: "Television",
  },
  {
    _id: uuid(),
    title: "Soundbar",
    brand: "Zebronics",
    price: "1000",
    priceBefore:"2000",
    discount:"50",
    rating:"5",
    inStock:true,
    isFeatured:false,
    isLatest:true,
    badge:"NEW",
    imgSrc:product2,
    categoryName: "Television",
  },
  {
    _id: uuid(),
    title: "Ultra HD (4K) LED Smart",
    brand: "Motorola",
    price: "6000",
    priceBefore:"8000",
    discount:"10",
    rating:"4",
    inStock:true,
    isFeatured:false,
    isLatest:true,
    badge:"BESTSELLER",
    imgSrc:product3,
    categoryName: "Television",
  },
  {
    _id: uuid(),
    title: "Ultra HD (4K) LED Smart",
    brand: "Motorola",
    price: "9000",
    priceBefore:"16000",
    discount:"10",
    rating:"2",
    inStock:true,
    isFeatured:true,
    isLatest:false,
    badge:"",
    imgSrc:product4,
    categoryName: "Television",
  },
  {
    _id: uuid(),
    title: "Ultra HD (4K) LED Smart",
    brand: "Motorola",
    price: "9000",
    priceBefore:"15000",
    discount:"10",
    rating:"5",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product5,
    categoryName: "Television",
  },
  {
    _id: uuid(),
    title: "Ultra HD (4K) LED Smart",
    brand: "Motorola",
    price: "5500",
    priceBefore:"10000",
    discount:"50",
    rating:"2.5",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product6,
    categoryName: "Television",
  },
  {
    _id: uuid(),
    title: "New Smartphone",
    brand: "oneplus",
    price: "9000",
    priceBefore:"16000",
    discount:"40",
    rating:"3",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product7,
    categoryName: "Smartphone",
  },
  {
    _id: uuid(),
    title: "New Smartphone",
    brand: "Nokia",
    price: "7000",
    priceBefore:"10000",
    discount:"30",
    rating:"5",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product8,
    categoryName: "Smartphone",
  },
  {
    _id: uuid(),
    title: "New Smartphone",
    brand: "onePlus",
    price: "4500",
    priceBefore:"9000",
    discount:"30",
    rating:"4.4",
    inStock:true,
    isFeatured:true,
    isLatest:true,
    badge:"NEW",
    imgSrc:product9,
    categoryName: "Smartphone",
  },
  {
    _id: uuid(),
    title: "New Smartphone",
    brand: "Nokia",
    price: "8000",
    priceBefore:"12000",
    discount:"50",
    rating:"3.5",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product10,
    categoryName: "Smartphne",
  },
  {
    _id: uuid(),
    title: "New Smartphone",
    brand: "onePlus",
    price: "5000",
    priceBefore:"6000",
    discount:"50",
    rating:"4",
    inStock:true,
    isFeatured:false,
    isLatest:true,
    badge:"NEW",
    imgSrc:product11,
    categoryName: "Smartphone",
  },
  {
    _id: uuid(),
    title: "Laptop",
    brand: "Asus",
    price: "8000",
    priceBefore:"16000",
    discount:"20",
    rating:"4.5",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product12,
    categoryName: "Laptop",
  },
  {
    _id: uuid(),
    title: "Laptop",
    brand: "pixel",
    price: "15000",
    priceBefore:"19000",
    discount:"50",
    rating:"3",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product13,
    categoryName: "Laptop",
  },
  {
    _id: uuid(),
    title: "Laptop",
    brand: "HP",
    price: "15000",
    priceBefore:"16000",
    discount:"10",
    rating:"4",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product14,
    categoryName: "Laptop",
  },
  {
    _id: uuid(),
    title: "Laptop",
    brand: "Apple",
    price: "50000",
    priceBefore:"66000",
    discount:"50",
    rating:"4.7",
    inStock:true,
    isFeatured:true,
    isLatest:false,
    badge:"BESTSELLER",
    imgSrc:product15,
    categoryName: "Laptop",
  },
  {
    _id: uuid(),
    title: "Desktop",
    brand: "HP",
    price: "15000",
    priceBefore:"16000",
    discount:"20",
    rating:"2",
    inStock:true,
    isFeatured:true,
    isLatest:false,
    badge:"",
    imgSrc:product16,
    categoryName: "Laptop",
  },
  {
    _id: uuid(),
    title: "Mixer Grinder",
    brand: "philips",
    price: "7600",
    priceBefore:"9600",
    discount:"16",
    rating:"3.6",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"BESTSELLER",
    imgSrc:product17,
    categoryName: "HomeAppliances",
  },
  {
    _id: uuid(),
    title: "Air Conditioner",
    brand: "Bosch",
    price: "9500",
    priceBefore:"10000",
    discount:"10",
    rating:"4",
    inStock:false,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product18,
    categoryName: "HomeAppliances",
  },
  {
    _id: uuid(),
    title: " Bluetooth Home Theatre",
    brand: "Motorola",
    price: "6500",
    priceBefore:"7000",
    discount:"10",
    rating:"1",
    inStock:true,
    isFeatured:true,
    isLatest:true,
    badge:"NEW",
    imgSrc:product19,
    categoryName: "Television",
  },
  {
    _id: uuid(),
    title: "Hair Dryer",
    brand: "philips",
    price: "2000",
    priceBefore:"4000",
    discount:"50",
    rating:"2",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product20,
    categoryName: "HomeAppliances",
  },
  {
    _id: uuid(),
    title: "Portbale AC",
    brand: "Philips",
    priceBefore:"10000",
    price: "5000",
    discount:"50",
    rating:"4",
    inStock:true,
    isFeatured:true,
    isLatest:false,
    badge:"BESTSELLER",
    imgSrc:product21,
    categoryName: "HomeAppliances",
  },
  {
    _id: uuid(),
    title: "Washing Machine",
    brand: "Samsung",
    price: "4000",
    priceBefore:"8000",
    discount:"30",
    rating:"4",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product22,
    categoryName: "HomeAppliances",
  },
  {
    _id: uuid(),
    title: "Induction stove",
    brand: "Prestige",
    price: "7000",
    priceBefore:"16000",
    discount:"40",
    rating:"4",
    inStock:true,
    isFeatured:false,
    isLatest:false,
    badge:"",
    imgSrc:product23,
    categoryName: "HomeAppliances",
  },
]
